name: build

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'docs/**'
    pull_request:
        branches:
            - main
        paths-ignore:
            - 'docs/**'

permissions:
    actions: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js (from .nvmrc)
              uses: actions/setup-node@v3
              with:
                  node-version-file: .nvmrc
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Type-check
              run: npm run typecheck

            - name: Lint
              run: npm run lint

            - name: Format
              run: npm run format

            - name: Build
              run: npm run build
